INSERT INTO Subject (Test)
SELECT DISTINCT UkrTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT histTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT mathTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT physTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT chemTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT bioTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT geoTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT engTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT fraTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT deuTest
FROM TestTable
ON CONFLICT DO NOTHING;

INSERT INTO Subject (Test)
SELECT DISTINCT spaTest
FROM TestTable
ON CONFLICT DO NOTHING;
