-- Insert students info
INSERT INTO StudentTable (OUTID,
                          Birth,
                          SexTypeName,
                          Regname,
                          AreaName,
                          TerName,
                          RegTypeName,
                          TerTypeName,
                          ClassProfileName,
                          ClassLangName,
                          EOName,
                          EOTypeName,
                          EORegName,
                          EOAreaName,
                          EOTerName,
                          EOParent,
                          ExamYear)
SELECT OUTID,
       Birth,
       SEXTYPENAME,
       REGNAME,
       AREANAME,
       TERNAME,
       REGTYPENAME,
       TerTypeName,
       ClassProfileNAME,
       ClassLangName,
       EONAME,
       EOTYPENAME,
       EORegName,
       EOAreaName,
       EOTerName,
       EOParent,
       examYear

FROM TestTable;
